# @package _group_
n_training_steps: 20000
database_name: trash.db
record_video: True
batch_size: 64
n_evaluation_episodes: 10
eval_every: 1000
train_every: 1
n_training_per_sample: 1
n_initial_samples: 100
log_freq: 100
